import Providers from "@/components/providers";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const pretendard = localFont({
  src: "../public/fonts/PretendardVariable.woff2",
  variable: "--font-pretendard",
});

const iropkeBatang = localFont({
  src: "../public/fonts/IropkeBatangM.otf",
  variable: "--font-batang",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${pretendard.variable} ${iropkeBatang.variable}`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
